# Generated by Django 5.1.6 on 2025-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_discountbycode_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_precentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
