# Generated by Django 5.1.6 on 2025-03-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_discount_precentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_precentage',
            new_name='discount_percentage',
        ),
    ]
