# Generated by Django 5.1.6 on 2025-03-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_description_category_image_discountbycode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
