# Generated by Django 5.1.6 on 2025-03-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_creat_at_tag_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='producut',
            new_name='product',
        ),
    ]
