# Generated by Django 5.1.6 on 2025-03-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_brand_slug_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
