# Generated by Django 5.1.6 on 2025-03-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
    ]
