# Generated by Django 5.1.6 on 2025-03-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_product_discountbycode_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountByCode',
        ),
    ]
